#!/bin/bash
## 09/03/19
##
## Name: CentOS_Wacom_fix.sh
## Desc: Disable Wacom Multi-Touch, ExpressKeys and Finger Wheel
## with minimal user interaction.  Add pointer from rc.local to persist
## after reboot.  Workaround available by request.
##
## Always Current Version:
##      https://github.com/flamescripts/Flame_Scripts
##
## Disclamer: This is not an official Autodesk certified script.  Neither the
## author nor Autodesk are responsible for any use, misuse, unintened results 
## or data loss that may ocurr from using this script.
##
## Use at your own risk.  Script intended for providing guidance only.
##
## Test Models: Intuos 4, Intuos Pro Medium, Intuos Pro Large, Intuos5 Touch Medium
## Test OS: Autodesk CentOS 7.2 ISO 1511 Rev 003 using ks.cfg
##
## IMPORTANT:  If using script remotely via ssh, be sure to export the DISPLAY
## ex: export DISPLAY=:0
##
##########################################################################

export DISPLAY=:0.0

# Variables
PAD=`xsetwacom --list devices | awk '/PAD/||/pad/||/Pad/' | awk -F "id:" '{print $1}' | cut -d " " -f1-8  | sed -e 's/[[:space:]]*$//'`
TOUCH=`xsetwacom --list devices | awk '/FINGER/||/finger/||/Finger/||/TOUCH/||/touch/||/Touch/' | awk -F "id:" '{print $1}' | cut -d " " -f1-8  | sed -e 's/[[:space:]]*$//'`
STYLUS=`xsetwacom --list devices | awk '/STYLUS/||/stylus/||/Stylus/' | awk -F "id:" '{print $1}' | cut -d " " -f1-8  | sed -e 's/[[:space:]]*$//'`
CURSOR=`xsetwacom --list devices | awk '/CURSOR/||/cursor/||/Cursor/' | awk -F "id:" '{print $1}' | cut -d " " -f1-8  | sed -e 's/[[:space:]]*$//'`
ERASER=`xsetwacom --list devices | awk '/ERASER/||/eraser/||/Eraser/' | awk -F "id:" '{print $1}' | cut -d " " -f1-8  | sed -e 's/[[:space:]]*$//'`
RING=( AbsWheelUp AbsWheelDown AbsWheel2Up AbsWheel2Down RelWheelUp RelWheelDown StripLeftUp StripLeftDown StripRightUp StripRightDown )

ZERO='button 0'
ZEROALT='0'


# SSH DISPLAY
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        clear
        echo "It looks like you are using a remote shell"
        echo "You MUST export display if errors occur: '${bold}export DISPLAY=:0'"
        read -n 1 -s -r -p "Press any key to continue"
fi


# Reset console
clear


# Model IDs for reference
echo 'CentOS Wacom fix script'
echo 'PAD:' $PAD
echo 'STYLUS:' $STYLUS
echo 'ERASER:' $ERASER
echo 'CURSOR:' $CURSOR

# Turn off touch
if [[ $TOUCH ]]; then
        echo 'TOUCH: ' $TOUCH
        echo
        echo '  Touch is currently turned:' `xsetwacom get "$TOUCH" TOUCH`
        echo
        echo 'Turning touch off'
                xsetwacom set "$TOUCH" TOUCH off
else
        echo 'TOUCH:  no touch feature detected on this Wacom tablet'
        echo
fi
